### ISSUE TITLE
LAPACK 3.10.0

### ISSUE THREAD

**Issue by Enchufa2** [mpimd-csc/flexiblas#14]
LAPACK 3.9.1 landed in Fedora rawhide a few days ago. I tried just rebuilding FlexiBLAS against it, but fails because the version is not recognized (I thought it would assume 3.9.0): https://kojipkgs.fedoraproject.org//work/tasks/3880/66393880/build.log

Is it safe to just specify `LAPACK_API_VERSION=3.9.0`? Or should I wait for an update?

**Comment by grisuthedragon** [comment]
Since no new routine was added, at least regarding the changelog, this is safe. The Fallback routines are taken from the static library you provide during build? So the ones from lapack  3.9.1 are used. The import of lapack 3.9.1  will be done in the 3.1 release coming up soon. 

Be aware that there seems to be some bug in LAPACK 3.9.1. See https://savannah.gnu.org/bugs/?60357

**Comment by Enchufa2** [comment]
FYI, LAPACK 3.10.0 is available in Fedora rawhide. :)

**Comment by grisuthedragon** [comment]
Thanks, I will include it in the next release. I think somewhen in August.

**Comment by Enchufa2** [comment]
Sounds good. I suppose that dependencies will require a rebuild against the new version, right? I'm asking because I _should_ avoid ABI/API changes after the Beta Freeze (which is on 2021-08-24). In this case, if we cannot make it, I suppose an exception can be made, because LAPACK 3.10.0 will be part of Fedora 35 anyways.

**Comment by grisuthedragon** [comment]
As long a no routines from the new LAPACK versions are used, which will be the case for all packages, a rebuild is not necessary, since the ABI with respect to the old LAPACK <= 3.8 stays the same.

**Comment by Enchufa2** [comment]
Great, then there's no hard deadline for Fedora 35. :)

**Comment by grisuthedragon** [comment]
Closed with 3.1.0
