### ISSUE TITLE
Int instead of int in standalone API

### ISSUE THREAD

**Issue by Enchufa2** [mpimd-csc/flexiblas#21]
I've noticed that a number of functions have changed from `int` to `Int` in `flexiblas_api.h`. They are equal per the define on top of that header, but shouldn't this change in `flexiblas_api_standalone.c` too?

**Comment by grisuthedragon** [comment]
Since some of the (the ones with `_` in the end) are meant to be called from Fortran, and thus affected by the 64 bit integer setting, they must return `Int` instead of `int` but you are right, this behaviour should be reflected by `flexiblas_api_standalone.c`. 

This will be included in the next bugfix release, when ever it is ready. For now, you can leave it as it is,

**Comment by Enchufa2** [comment]
Perfect. I include `flexiblas_api_standalone.c` in the R package [here](https://github.com/Enchufa2/r-flexiblas/blob/master/src/flexiblas_api_standalone.c). Should I patch it there to match the header?

**Comment by grisuthedragon** [comment]
fixed in 3.1.3.
